name: Build Data
on:
  push:
    branches: [ main ]
    paths:
      - 'content/**'
      - 'scripts/generate-content.js'
      - '.github/workflows/build-data.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm i

      - name: Generate JSON data
        run: npm run build:data

      - name: Commit generated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data/*.json
          git commit -m "chore(data): regenerate content JSON" || echo "No changes"
          git push
